name: 'custom_action'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  name: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'