name: checks
on: [pull_request, workflow_dispatch]

env:
  ACT_OWNER: ${{ github.repository_owner }}
  ACT_REPOSITORY: ${{ github.repository }}
  GO_VERSION: 1.18
  CGO_ENABLED: 0

jobs:
  print:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: ../rwf/custom_action@z
        with:
          name: ${{ env.ACT_OWNER }}
     