name: checks
on: [push, pull_request, workflow_dispatch]

env:
  ACT_OWNER: ${{ github.repository_owner }}
  ACT_REPOSITORY: ${{ github.repository }}
  GO_VERSION: 1.18
  CGO_ENABLED: 0

jobs:
  print:
    name: lint
    runs-on: ubuntu-latest
    steps:
#      - run: |
#          echo ${{ env.ACT_OWNER }}
#      #- uses: giacomobenedetti/security-test-ts@v1
      - uses: actions/checkout@v3
        with:
          repo: giacomobenedetti/security-test-ts

      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '# Message with markdown.\nThis is the message that will be displayed on users first issue.'
          pr-message: 'Message that will be displayed on users first pr. Look, a `code block` for markdown.'
